# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cmd: install
      - name: TSLinting check
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: ESLint check
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint
      - name: Test around
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:ci
      - name: Test build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:test
